In [55]:
import tensorflow
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [56]:
model=load_model('model.h5')
with open('onehot_encoder_geo.pkl','rb') as file:
    one_enc_geo=pickle.load(file)
with open('label_encoder_gender.pkl','rb') as file:
    label_enc=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [57]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [58]:
geo_hot=one_enc_geo.transform([[input_data['Geography']]]).toarray()
geo_hot_df=pd.DataFrame(geo_hot,columns=one_enc_geo.get_feature_names_out(['Geography']))
geo_hot_df

c:\Users\asus\Desktop\aidsml_engineering\AiMlDs_workspace\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [59]:
input_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [60]:
input_data_df=pd.DataFrame([input_data])
input_data_df

   CreditScore Geography Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France   Male  ...          1               1            50000

[1 rows x 10 columns]

In [61]:
input_data_df['Gender']=label_enc.transform([input_data_df['Gender']])
input_data_df

c:\Users\asus\Desktop\aidsml_engineering\AiMlDs_workspace\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [62]:
input_data_df=pd.concat([input_data_df.drop('Geography',axis=1),geo_hot_df],axis=1)

In [63]:
 input_scaled=scaler.transform(input_data_df)
 input_scaled

array([[-0.51953816,  0.90697312,  0.09769163, -0.68723876, -0.27077828,
         0.79337059,  0.64842466,  0.97497958, -0.87969019,  1.00213561,
        -0.5818665 , -0.57447633]])

In [64]:
predictions=model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step

In [65]:
prediction_prob=predictions[0][0]
prediction_prob

np.float32(0.043958865)

In [66]:
if prediction_prob>0.5:
    print("customer is likely to churn")
else:
    print("not likely to churn")

not likely to churn